name: Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-contract:
    name: Build ${{ matrix.contract }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        contract: [ intents-vault, solver-registry ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install cargo-near CLI
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/near/cargo-near/releases/download/cargo-near-v0.17.0/cargo-near-installer.sh | sh
      - name: Build ${{ matrix.contract }}
        run: cargo near build reproducible-wasm --manifest-path contracts/${{matrix.contract}}/Cargo.toml
